### ISSUE TITLE
Duplicate compositions in dataset

### ISSUE THREAD

**Issue by rubencart** [smashub/choco#113]
I'm assuming there are at least some compositions or songs that occur in several partitions (e.g. in Isophonics and Billboard). Is there an easy way to detect these? E.g. are annotations linked to compositions or songs by having an id not only of the annotation but of the composition the annotation is for?

**Comment by jonnybluesman** [comment]
Hi @rubencart, as ChoCo integrates harmonic datasets it is pretty normal that the same piece occurs more than once. Technically, these are not duplicates, because what this means is that we have more than 1 harmonic annotation for the same piece, which is a good thing. This may be detected from the knowledge graph when the song/piece receives the same URI from different JAMS files. Anyways, if you find more links within ChoCo, we will be happy to integrate them in future releases.

**Comment by rubencart** [comment]
OK I see the use of having different annotations for the same piece, but it would be useful to have an easy way to detect this. On the other hand even detecting it might not be super straightforward since what is a composition vs a song vs a performance vs a cover vs ... etc.
